// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/transfer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromAccountId int64                  `protobuf:"varint,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   int64                  `protobuf:"varint,3,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_proto_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_proto_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *Transfer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transfer) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *Transfer) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *Transfer) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transfer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccountId int64                  `protobuf:"varint,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   int64                  `protobuf:"varint,2,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_proto_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *TransferRequest) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *TransferRequest) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *TransferRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_proto_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *TransferResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *TransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTransferByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferByIDRequest) Reset() {
	*x = GetTransferByIDRequest{}
	mi := &file_proto_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferByIDRequest) ProtoMessage() {}

func (x *GetTransferByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTransferByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransferByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListTransfersByAccountIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransfersByAccountIDRequest) Reset() {
	*x = ListTransfersByAccountIDRequest{}
	mi := &file_proto_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransfersByAccountIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransfersByAccountIDRequest) ProtoMessage() {}

func (x *ListTransfersByAccountIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransfersByAccountIDRequest.ProtoReflect.Descriptor instead.
func (*ListTransfersByAccountIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_transfer_proto_rawDescGZIP(), []int{4}
}

func (x *ListTransfersByAccountIDRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

var File_proto_transfer_proto protoreflect.FileDescriptor

const file_proto_transfer_proto_rawDesc = "" +
	"\n" +
	"\x14proto/transfer.proto\x12\btransfer\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n" +
	"\bTransfer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x0ffrom_account_id\x18\x02 \x01(\x03R\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x03 \x01(\x03R\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"u\n" +
	"\x0fTransferRequest\x12&\n" +
	"\x0ffrom_account_id\x18\x01 \x01(\x03R\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x02 \x01(\x03R\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"\\\n" +
	"\x10TransferResponse\x12.\n" +
	"\btransfer\x18\x01 \x01(\v2\x12.transfer.TransferR\btransfer\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"(\n" +
	"\x16GetTransferByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"@\n" +
	"\x1fListTransfersByAccountIDRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId2\x80\x02\n" +
	"\x0fTransferService\x12G\n" +
	"\x0eCreateTransfer\x12\x19.transfer.TransferRequest\x1a\x1a.transfer.TransferResponse\x12G\n" +
	"\x0fGetTransferByID\x12 .transfer.GetTransferByIDRequest\x1a\x12.transfer.Transfer\x12[\n" +
	"\x18ListTransfersByAccountID\x12).transfer.ListTransfersByAccountIDRequest\x1a\x12.transfer.Transfer0\x01B\aZ\x05./;pbb\x06proto3"

var (
	file_proto_transfer_proto_rawDescOnce sync.Once
	file_proto_transfer_proto_rawDescData []byte
)

func file_proto_transfer_proto_rawDescGZIP() []byte {
	file_proto_transfer_proto_rawDescOnce.Do(func() {
		file_proto_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transfer_proto_rawDesc), len(file_proto_transfer_proto_rawDesc)))
	})
	return file_proto_transfer_proto_rawDescData
}

var file_proto_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_transfer_proto_goTypes = []any{
	(*Transfer)(nil),                        // 0: transfer.Transfer
	(*TransferRequest)(nil),                 // 1: transfer.TransferRequest
	(*TransferResponse)(nil),                // 2: transfer.TransferResponse
	(*GetTransferByIDRequest)(nil),          // 3: transfer.GetTransferByIDRequest
	(*ListTransfersByAccountIDRequest)(nil), // 4: transfer.ListTransfersByAccountIDRequest
	(*timestamppb.Timestamp)(nil),           // 5: google.protobuf.Timestamp
}
var file_proto_transfer_proto_depIdxs = []int32{
	5, // 0: transfer.Transfer.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: transfer.TransferResponse.transfer:type_name -> transfer.Transfer
	1, // 2: transfer.TransferService.CreateTransfer:input_type -> transfer.TransferRequest
	3, // 3: transfer.TransferService.GetTransferByID:input_type -> transfer.GetTransferByIDRequest
	4, // 4: transfer.TransferService.ListTransfersByAccountID:input_type -> transfer.ListTransfersByAccountIDRequest
	2, // 5: transfer.TransferService.CreateTransfer:output_type -> transfer.TransferResponse
	0, // 6: transfer.TransferService.GetTransferByID:output_type -> transfer.Transfer
	0, // 7: transfer.TransferService.ListTransfersByAccountID:output_type -> transfer.Transfer
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_transfer_proto_init() }
func file_proto_transfer_proto_init() {
	if File_proto_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transfer_proto_rawDesc), len(file_proto_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transfer_proto_goTypes,
		DependencyIndexes: file_proto_transfer_proto_depIdxs,
		MessageInfos:      file_proto_transfer_proto_msgTypes,
	}.Build()
	File_proto_transfer_proto = out.File
	file_proto_transfer_proto_goTypes = nil
	file_proto_transfer_proto_depIdxs = nil
}
